timeout: 0
serial: yes

/mitosOS (Limine protocol)
    protocol: limine
    path: boot():/boot/mitosos.elf
    module_path: boot():/boot/rootfs.tar

/mitosOS (Multiboot2)
    protocol: multiboot2
    path: boot():/boot/mitosos.elf
    module_path: boot():/boot/rootfs.tar
