# limine.conf -- see https://github.com/Limine-Bootloader/Limine/blob/trunk/CONFIG.md

timeout: 0
serial: yes

/mitosOS (Multiboot2)
    protocol: multiboot2
    path: boot():/boot/mitosos.elf
    module_path: boot():/boot/rootfs.tar

/mitosOS (Limine protocol)
    protocol: limine
    path: boot():/boot/mitosos.elf
    module_path: boot():/boot/rootfs.tar
